FROM docker.io/node:26-alpine@sha256:ef24c5053d50fdc3e4e56eb4e7ddb7861874ab0fdc797046ba897581deb8e868 AS builder

ARG GIT_REF
ARG PACKAGE

RUN apk add --no-cache git

RUN npm install -g pnpm@10.34.1

RUN git clone --depth 1 --branch "${GIT_REF}" https://github.com/owncloud/web-extensions.git /build

WORKDIR /build
RUN pnpm install --frozen-lockfile
RUN pnpm --filter "./packages/web-app-${PACKAGE}" build


FROM nginxinc/nginx-unprivileged:alpine@sha256:b54ac358b83fc6c965793fd271839b4ea4cdb6e99895bb19618cbc2ca152d972

ARG PACKAGE
ARG VERSION=""
ARG REVISION=""

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Web Extensions" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud Web Extensions - community and supplementary extensions for the ownCloud Web frontend" \
  org.opencontainers.image.licenses="Apache-2.0" \
  org.opencontainers.image.documentation="https://github.com/owncloud/web-extensions" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/web-extensions" \
  org.opencontainers.image.source="https://github.com/owncloud/web-extensions" \
  org.opencontainers.image.version="${VERSION}" \
  org.opencontainers.image.revision="${REVISION}"

USER root

RUN apk upgrade --no-cache

RUN rm -f /usr/share/nginx/html/*

COPY --from=builder /build/packages/web-app-${PACKAGE}/dist /usr/share/nginx/html/${PACKAGE}

EXPOSE 8080/tcp

WORKDIR /usr/share/nginx/html

USER nginx

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
