FROM docker.io/node:24-alpine@sha256:50c8e8ca1d27439048670df5883f32d57cf81cff6233222c893fd0d9884cbd81 AS builder

ARG GIT_REF
ARG PACKAGE

RUN apk add --no-cache git

RUN npm install -g pnpm@10.34.1

RUN git clone --depth 1 --branch "${GIT_REF}" https://github.com/owncloud/web-extensions.git /build

WORKDIR /build
RUN pnpm install --frozen-lockfile
RUN pnpm --filter "./packages/web-app-${PACKAGE}" build


FROM owncloudops/nginx@sha256:8ca0c90c2f537fef6195ba8f5ebe6d6c00fe0a0c545f25ce8acd418a831a19a4

ARG PACKAGE
ARG VERSION=""
ARG REVISION=""

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Web Extensions" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud Web Extensions - community and supplementary extensions for the ownCloud Web frontend" \
  org.opencontainers.image.licenses="Apache-2.0" \
  org.opencontainers.image.documentation="https://github.com/owncloud/web-extensions" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/web-extensions" \
  org.opencontainers.image.source="https://github.com/owncloud/web-extensions" \
  org.opencontainers.image.version="${VERSION}" \
  org.opencontainers.image.revision="${REVISION}"

RUN rm -f /var/lib/nginx/html/*

COPY --from=builder /build/packages/web-app-${PACKAGE}/dist /var/lib/nginx/html/${PACKAGE}

EXPOSE 8080/tcp

WORKDIR /var/lib/nginx/html

USER nginx

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
